# Configuration for TDA Hyperparameters

# --- Positive Cache Configuration ---
positive:
  enabled: True
  shot_capacity: 9
  alpha: 1.0
  beta: 8.0 
  pos_similarity_threshold: 0.87475

# --- Negative Cache Configuration ---
negative:
  enabled: True
  shot_capacity: 10
  alpha: 0.117
  beta: 1.0
  neg_similarity_threshold: 0.70494
  entropy_threshold:
    lower: 0.2
    upper: 0.5 
  mask_threshold:
    lower: 0.03
    upper: 1.0