<<<<<<< HEAD
# Configuration for TDA Hyperparameters

# --- Positive Cache Configuration ---
positive:
  enabled: True
  shot_capacity: 2
  alpha: 2.0
  beta: 5.0 
  pos_similarity_threshold: 0.91

# --- Negative Cache Configuration ---
negative:
  enabled: True
  shot_capacity: 2
  alpha: 0.117
  beta: 1.0
  neg_similarity_threshold: 0.81
  entropy_threshold:
    lower: 0.2
    upper: 0.5 
  mask_threshold:
    lower: 0.03
=======
# Configuration for TDA Hyperparameters

# --- Positive Cache Configuration ---
positive:
  enabled: True
  shot_capacity: 3
  alpha: 2.0
  beta: 5.0 

# --- Negative Cache Configuration ---
negative:
  enabled: True
  shot_capacity: 2
  alpha: 0.117
  beta: 1.0
  entropy_threshold:
    lower: 0.2
    upper: 0.5 
  mask_threshold:
    lower: 0.03
>>>>>>> dbba8e6341b254ea826b5e2215558f268e46f67e
    upper: 1.0